# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: b1305c10d8b5c7fbccbe92166d0389aef71e73f7b840193146d40a651775b44aeadfa5981dfcd549738fd80147bdd5deef1ba64acee8db0ce34a39f584917a58

test:
  secret_key_base: 41074a4616798fbe9d8f9ca9ec2476baaa2a338546c19d7529ee937b30de3a21134282aab9b9d4a61a50aa5d62d0353f276f1594e504b241343ad4bfc8ee3850

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
